const CONVENCIONES = [
  // ==================== ENERO (mesIdx: 0) ====================
  {
    id: 'la-sagrera-juga',
    nombre: 'La Sagrera Juga',
    fechas: '10 Enero 2026',
    fechaInicioISO: '2026-01-10T10:00:00',
    finDeSemanaClave: '2026-W02',
    mesIdx: 0,
    comunidad: 'Cataluña',
    ciudad: 'Barcelona',
    recinto: 'Espai Polivalent La Sagrera',
    direccion: 'Espai Polivalent La Sagrera, Carrer de Martí Molins, 29, Sant Andreu, 08027 Barcelona',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Juegos de Mesa', 'Ludoteca'],
    descripcion: 'Jornadas de juegos de mesa y ocio lúdico.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: '#'
  },
  {
    id: 'winter-freak-torre-pacheco',
    nombre: 'Winter Freak',
    fechas: '17 - 18 Enero 2026',
    fechaInicioISO: '2026-01-17T10:00:00',
    finDeSemanaClave: '2026-W03',
    mesIdx: 0,
    comunidad: 'Región de Murcia',
    ciudad: 'Torre-Pacheco (Murcia)',
    recinto: 'IFEPA',
    direccion: 'IFEPA, Av. de Gerardo Molina, 45, 30700 Torre-Pacheco, Murcia',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Manga', 'Ocio Alternativo'],
    descripcion: 'Salón del manga y ocio alternativo de invierno.',
    tienePrograma: false,
    cartel: 'https://ifepa.es/wp-content/uploads/2023/07/sabado-imagen-producto-01-768x1086-1.jpg',
    enlaceExterno: 'https://universofreak.com/'
  },

  // ==================== FEBRERO (mesIdx: 1) ====================
  {
    id: 'manga-calella',
    nombre: '5è Saló del Manga de Calella',
    fechas: '7 - 8 Febrero 2026',
    fechaInicioISO: '2026-02-07T10:00:00',
    finDeSemanaClave: '2026-W06',
    mesIdx: 1,
    comunidad: 'Cataluña',
    ciudad: 'Calella (Barcelona)',
    recinto: 'Fàbrica Llobet-Guri',
    direccion: 'Fàbrica Llobet-Guri, Carrer de Sant Jaume, 321, 08370 Calella, Barcelona',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Manga Comarcal', 'Cosplay'],
    descripcion: 'Manga comarcal, cosplay y cultura nipona.',
    tienePrograma: false,
    cartel: 'https://www.turismemaresme.cat/media/upload/cache/7_i_8_FEBRER_1769767055_w649webp.webp',
    enlaceExterno: 'https://www.calellabarcelona.com/es/planifica/eventos/salo-manga-calella/'
  },
  {
    id: 'jw-madrid-invierno',
    nombre: 'Japan Weekend Madrid Invierno',
    fechas: '14 - 15 Febrero 2026',
    fechaInicioISO: '2026-02-14T10:00:00',
    finDeSemanaClave: '2026-W07',
    mesIdx: 1,
    comunidad: 'Madrid',
    ciudad: 'Madrid Capital',
    recinto: 'IFEMA Madrid (Pabellones 4, 6 y 8)',
    direccion: 'IFEMA Madrid, Av. del Partenón, 5, Barajas, 28042 Madrid',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Manga', 'Anime', 'Cosplay Summit'],
    descripcion: 'Manga, anime y cosplay en IFEMA.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://japanweekend.com/madrid/'
  },
  {
    id: 'comic-valencia-feb',
    nombre: 'Salón del Cómic de València',
    fechas: '27 Feb - 1 Mar 2026',
    fechaInicioISO: '2026-02-27T10:00:00',
    finDeSemanaClave: '2026-W09',
    mesIdx: 1,
    comunidad: 'Comunitat Valenciana',
    ciudad: 'Valencia Capital',
    recinto: 'Feria Valencia',
    direccion: 'Feria Valencia, Avinguda de les Fires, s/n, Pobles de l\'Oest, 46035 València',
    categoria: 'comic',
    estado: 'PROGRAMA OFICIAL',
    badges: ['Editorial', 'Firmas', 'Autores'],
    descripcion: 'Gran salón editorial levantino con autores y exposiciones.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://saloncomicvalencia.com'
  },
  {
    id: 'jornades-rol-sant-sadurni',
    nombre: 'XXI Jornades de Rol',
    fechas: '28 Febrero 2026',
    fechaInicioISO: '2026-02-28T10:00:00',
    finDeSemanaClave: '2026-W09',
    mesIdx: 1,
    comunidad: 'Cataluña',
    ciudad: "Sant Sadurní d'Anoia (Barcelona)",
    recinto: 'Casal d\'Entitats',
    direccion: 'Casal d\'Entitats, Carrer de Marc Mir, 15, 08770 Sant Sadurní d\'Anoia, Barcelona',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Rol', 'Wargames'],
    descripcion: 'Encuentro de rol y wargames.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: '#'
  },

  // ==================== MARZO (mesIdx: 2) ====================
  {
    id: 'freakcon-torremolinos',
    nombre: 'FreakCon Torremolinos',
    fechas: '7 - 8 Marzo 2026',
    fechaInicioISO: '2026-03-07T10:00:00',
    finDeSemanaClave: '2026-W10',
    mesIdx: 2,
    comunidad: 'Andalucía',
    ciudad: 'Torremolinos (Málaga)',
    recinto: 'Palacio de Congresos de Torremolinos',
    direccion: 'Palacio de Congresos y Exposiciones de la Costa del Sol, C. México, 3, 29620 Torremolinos, Málaga',
    categoria: 'comic',
    estado: 'PROGRAMA OFICIAL',
    badges: ['Series', 'Retro', 'Doblaje'],
    descripcion: 'Series, retro y doblaje en la Costa del Sol.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://freakcon.es'
  },
  {
    id: 'graf-bcn',
    nombre: 'GRAF BCN',
    fechas: '14 - 15 Marzo 2026',
    fechaInicioISO: '2026-03-14T11:00:00',
    finDeSemanaClave: '2026-W11',
    mesIdx: 2,
    comunidad: 'Cataluña',
    ciudad: 'Barcelona Capital',
    recinto: 'Fabra i Coats',
    direccion: 'Fabra i Coats: Fàbrica de Creació, Carrer de Sant Adrià, 20, Sant Andreu, 08030 Barcelona',
    categoria: 'comic',
    estado: 'CONFIRMADO',
    badges: ['Cómic de Autor', 'Autoedición'],
    descripcion: 'Cómic de autor y autoedición en Fabra i Coats.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://grafcomic.com'
  },
  {
    id: 'jw-bcn',
    nombre: 'Japan Weekend Barcelona',
    fechas: '14 - 15 Marzo 2026',
    fechaInicioISO: '2026-03-14T10:00:00',
    finDeSemanaClave: '2026-W11',
    mesIdx: 2,
    comunidad: 'Cataluña',
    ciudad: "L'Hospitalet de Llobregat (Barcelona)",
    recinto: 'Fira Barcelona - Gran Via (Pabellón 6)',
    direccion: 'Fira Barcelona Gran Via - Pabellón 6, Av. Joan Carles I, 64, 08908 L’Hospitalet de Llobregat, Barcelona',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Cultura Nipona', 'Gaming', 'Cosplay'],
    descripcion: 'Cultura nipona y gaming en Fira Barcelona Gran Via.',
    tienePrograma: false,
    cartel: 'https://www.japanweekend.com/barcelona/wp-content/uploads/sites/5/2026/04/lowres-scaled.jpg',
    enlaceExterno: 'https://japanweekend.com/barcelona/'
  },
  {
    id: 'ficzone-granada',
    nombre: 'FicZone, Granada Gaming & Meeple Factory',
    fechas: '21 - 22 Marzo 2026',
    fechaInicioISO: '2026-03-21T10:00:00',
    finDeSemanaClave: '2026-W12',
    mesIdx: 2,
    comunidad: 'Andalucía',
    ciudad: 'Granada (Armilla)',
    recinto: 'FERMASA',
    direccion: 'FERMASA, Ctra. de Armilla, s/n, 18100 Armilla, Granada',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Cómic', 'Rol', 'Videojuegos'],
    descripcion: 'Cómic, rol y videojuegos en Fermasa.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://ficzone.com'
  },
  {
    id: 'jw-coruna',
    nombre: 'Japan Weekend A Coruña',
    fechas: '28 - 29 Marzo 2026',
    fechaInicioISO: '2026-03-28T10:00:00',
    finDeSemanaClave: '2026-W13',
    mesIdx: 2,
    comunidad: 'Galicia',
    ciudad: 'A Coruña',
    recinto: 'ExpoCoruña',
    direccion: 'ExpoCoruña, Rúa Juana Capdevielle, 2, 15008 A Coruña',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Manga', 'Ocio Alternativo'],
    descripcion: 'Manga y ocio alternativo en Galicia.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://japanweekend.com/coruna/'
  },
  {
    id: 'sakura-fest-gava',
    nombre: 'Sakura Fest Gavà',
    fechas: '29 Marzo 2026',
    fechaInicioISO: '2026-03-29T10:00:00',
    finDeSemanaClave: '2026-W13',
    mesIdx: 2,
    comunidad: 'Cataluña',
    ciudad: 'Gavà (Barcelona)',
    recinto: 'Espai Maragall',
    direccion: 'Espai Maragall, Passeig de Joan Maragall, 11, 08850 Gavà, Barcelona',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Cultura Asiática', 'Cosplay'],
    descripcion: 'Festival de cultura asiática y cosplay.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://www.instagram.com/sakurafestgava/'
  },

  // ==================== ABRIL (mesIdx: 3) ====================
 {
    id: 'expotaku-zaragoza',
    nombre: 'ExpOtaku Zaragoza',
    fechas: '19 - 21 Junio 2026',
    fechaInicioISO: '2026-06-19T10:00:00',
    finDeSemanaClave: '2026-W25',
    mesIdx: 5,
    comunidad: 'Aragón',
    ciudad: 'Zaragoza',
    recinto: 'Sala Multiusos del Auditorio de Zaragoza',
    direccion: 'Auditorio de Zaragoza - Sala Multiusos, C. de Violante de Hungría, 10, Universidad, 50009 Zaragoza',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Gira Anime', 'K-Pop'],
    descripcion: 'Gira anime y K-Pop en la Sala Multiusos.',
    tienePrograma: false,
    cartel: 'https://www.expotaku.com/imagenes/EOZ2026.jpg',
    enlaceExterno: 'https://expotaku.com/zaragoza'
  },
 {
    id: 'salon-manga-alicante',
    nombre: 'Salón del Manga de Alicante',
    fechas: '28 - 29 Marzo 2026',
    fechaInicioISO: '2026-03-28T10:00:00',
    finDeSemanaClave: '2026-W13',
    mesIdx: 2,
    comunidad: 'Comunitat Valenciana',
    ciudad: 'Elche / Alicante',
    recinto: 'IFA - Fira Alacant',
    direccion: 'IFA - Fira Alacant, N-340, km 731, 03320 Elx, Alicante',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Cultura Japonesa', 'Talleres', 'Videojuegos'],
    descripcion: 'Cultura tradicional japonesa, manga, anime, masterclasses, talleres gastronómicos, artes marciales y videojuegos.',
    tienePrograma: false,
    cartel: 'https://www.japanweekend.com/alicante/wp-content/uploads/sites/7/2026/03/Web-lowres-730x1024.jpg',
    enlaceExterno: 'https://www.japanweekend.com/alicante/'
  },
  {
    id: 'roledcon-bcn',
    nombre: 'V RoleDCon',
    fechas: '18 - 19 Abril 2026',
    fechaInicioISO: '2026-04-18T10:00:00',
    finDeSemanaClave: '2026-W16',
    mesIdx: 3,
    comunidad: 'Cataluña',
    ciudad: 'Barcelona Capital',
    recinto: 'Cotxeres de Sants',
    direccion: 'Cotxeres de Sants, Carrer de Sants, 79, Sants-Montjuïc, 08014 Barcelona',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Rol', 'Narrativa'],
    descripcion: 'Jornadas de rol y narrativa.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://nivel20.com/events/roledcon-v-edicion'
  },
  {
    id: 'salon-manga-jerez-primavera',
    nombre: 'Salón Manga de Jerez Primavera',
    fechas: '25 - 26 Abril 2026',
    fechaInicioISO: '2026-04-25T10:00:00',
    finDeSemanaClave: '2026-W17',
    mesIdx: 3,
    comunidad: 'Andalucía',
    ciudad: 'Jerez de la Frontera (Cádiz)',
    recinto: 'IFECA',
    direccion: 'IFECA, Parque González Hontoria, s/n, 11405 Jerez de la Frontera, Cádiz',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Cita Histórica', 'Cosplay'],
    descripcion: 'Cita histórica andaluza del manga.',
    tienePrograma: false,
    cartel: 'https://www.expotaku.com/imagenes/EOJ2026.jpg',
    enlaceExterno: 'https://www.expotaku.com/jerez/'
  },

  // ==================== MAYO (mesIdx: 4) ====================
  {
    id: 'comic-bcn-may',
    nombre: '44 Comic Barcelona',
    fechas: '8 - 10 Mayo 2026',
    fechaInicioISO: '2026-05-08T10:00:00',
    finDeSemanaClave: '2026-W19',
    mesIdx: 4,
    comunidad: 'Cataluña',
    ciudad: 'Barcelona Capital',
    recinto: 'Fira Barcelona Montjuïc',
    direccion: 'Fira de Barcelona - Montjuïc, Av. de la Reina Maria Cristina, s/n, 08004 Barcelona',
    categoria: 'comic',
    estado: 'PROGRAMA OFICIAL',
    badges: ['Cita Cómic Nacional', 'Premios', 'Firmas'],
    descripcion: 'Cita anual del cómic nacional.',
    tienePrograma: false,
    cartel: 'https://docs.ficomic.com/IMAGES_3/35446/400_x_44cb-cartell1.png',
    enlaceExterno: 'https://comic-barcelona.com'
  },
  {
    id: 'retro-barcelona',
    nombre: 'Retro Barcelona',
    fechas: '16 - 17 Mayo 2026',
    fechaInicioISO: '2026-05-16T10:00:00',
    finDeSemanaClave: '2026-W20',
    mesIdx: 4,
    comunidad: 'Cataluña',
    ciudad: "L'Hospitalet de Llobregat (Barcelona)",
    recinto: 'La Farga de L\'Hospitalet',
    direccion: 'La Farga Centro de Actividades, Carrer de Barcelona, 2, 08901 L\'Hospitalet de Llobregat, Barcelona',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Retro Gaming', 'Arcades', 'Clásicos'],
    descripcion: 'Videojuegos clásicos, arcades y microinformática.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://retrobarcelona.org'
  },
  {
    id: 'expotaku-sabadell',
    nombre: 'ExpOtaku Sabadell',
    fechas: '16 - 17 Mayo 2026',
    fechaInicioISO: '2026-05-16T10:00:00',
    finDeSemanaClave: '2026-W20',
    mesIdx: 4,
    comunidad: 'Cataluña',
    ciudad: 'Sabadell (Barcelona)',
    recinto: 'Fira Sabadell',
    direccion: 'Fira Sabadell, Plaça de la Sardana, 7, 08203 Sabadell, Barcelona',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Manga', 'K-Pop', 'Artist Alley'],
    descripcion: 'Manga, K-Pop y Artist Alley.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://expotaku.com/sabadell'
  },
  {
    id: 'expotaku-almeria',
    nombre: 'ExpOtaku Almería',
    fechas: '16 - 17 Mayo 2026',
    fechaInicioISO: '2026-05-16T10:00:00',
    finDeSemanaClave: '2026-W20',
    mesIdx: 4,
    comunidad: 'Andalucía',
    ciudad: 'Aguadulce (Almería)',
    recinto: 'Palacio de Exposiciones de Aguadulce',
    direccion: 'Palacio de Congresos y Exposiciones de Aguadulce, Av. de Pedro Muñoz Seca, s/n, 04720 Aguadulce, Almería',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Torneos Gaming', 'Cosplay'],
    descripcion: 'Torneos gaming y cosplay en Aguadulce.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://expotaku.com/almeria'
  },
  {
    id: 'albanime-albacete',
    nombre: 'Albanime Albacete',
    fechas: '23 - 24 Mayo 2026',
    fechaInicioISO: '2026-05-23T10:00:00',
    finDeSemanaClave: '2026-W21',
    mesIdx: 4,
    comunidad: 'Castilla-La Mancha',
    ciudad: 'Albacete',
    recinto: 'IFAB',
    direccion: 'IFAB - Institución Ferial de Albacete, C. Ejido, 4, 02005 Albacete',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Manga', 'Cultura Nipona'],
    descripcion: 'Salón del manga y cultura nipona en IFAB.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://albanime.com'
  },
  {
    id: 'otakubages-manresa',
    nombre: 'OtakuBages',
    fechas: '23 - 24 Mayo 2026',
    fechaInicioISO: '2026-05-23T10:00:00',
    finDeSemanaClave: '2026-W21',
    mesIdx: 4,
    comunidad: 'Cataluña',
    ciudad: 'Manresa (Barcelona)',
    recinto: 'Palau Firal de Manresa',
    direccion: 'Palau Firal de Manresa, Polígon Industrial els Dolors, Carrer Castelladral, 5-7, 08243 Manresa, Barcelona',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Manga Comarcal', 'Juvenil'],
    descripcion: 'Manga comarcal y actividades juveniles.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://www.instagram.com/otakubages/'
  },
  {
    id: 'jw-valencia-primavera',
    nombre: 'Japan Weekend Valencia Primavera',
    fechas: '30 - 31 Mayo 2026',
    fechaInicioISO: '2026-05-30T10:00:00',
    finDeSemanaClave: '2026-W22',
    mesIdx: 4,
    comunidad: 'Comunitat Valenciana',
    ciudad: 'Valencia Capital',
    recinto: 'Feria Valencia',
    direccion: 'Feria Valencia, Avinguda de les Fires, s/n, Pobles de l\'Oest, 46035 València',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Manga', 'Música Japonesa'],
    descripcion: 'Manga y música japonesa en Feria Valencia.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://japanweekend.com/valencia/'
  },

  // ==================== JUNIO (mesIdx: 5) ====================
  {
    id: 'vic-freak',
    nombre: 'Vic Freak',
    fechas: '6 - 7 Junio 2026',
    fechaInicioISO: '2026-06-06T10:00:00',
    finDeSemanaClave: '2026-W23',
    mesIdx: 5,
    comunidad: 'Cataluña',
    ciudad: 'Vic (Barcelona)',
    recinto: 'Recinte Firal el Sucre',
    direccion: 'Recinte Firal el Sucre, Carrer de l\'Historiador Ramon d\'Abadal i de Vinyals, 5, 08500 Vic, Barcelona',
    categoria: 'comic',
    estado: 'CONFIRMADO',
    badges: ['Cultura Pop', 'Cine', 'Retro'],
    descripcion: 'Cultura pop, cine y coleccionismo retro.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://vicfreak.cat'
  },
  {
    id: 'expotaku-madrid',
    nombre: 'ExpOtaku Madrid',
    fechas: '13 - 14 Junio 2026',
    fechaInicioISO: '2026-06-13T10:00:00',
    finDeSemanaClave: '2026-W24',
    mesIdx: 5,
    comunidad: 'Madrid',
    ciudad: 'Madrid Capital',
    recinto: 'Pabellón de Cristal (Casa de Campo)',
    direccion: 'Pabellón de Cristal, C. de las Aves, s/n, Moncloa - Aravaca, 28011 Madrid',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Salón Otaku', 'K-Pop'],
    descripcion: 'Salón otaku y K-Pop en Pabellón de Cristal.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://expotaku.com/madrid'
  },
  {
    id: 'mangafest-sevilla-summer',
    nombre: 'Mangafest Sevilla Summer',
    fechas: '20 - 21 Junio 2026',
    fechaInicioISO: '2026-06-20T10:00:00',
    finDeSemanaClave: '2026-W25',
    mesIdx: 5,
    comunidad: 'Andalucía',
    ciudad: 'Sevilla',
    recinto: 'FIBES Sevilla',
    direccion: 'FIBES - Palacio de Congresos y Exposiciones, Av. Alcalde Luis Uruñuela, 1, 41020 Sevilla',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Gaming Estival', 'Cultura Digital'],
    descripcion: 'Gaming y cultura digital estival en FIBES.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://mangafest.es'
  },
  {
    id: 'santander-comic',
    nombre: 'Santander Cómic & Ocio Alternativo',
    fechas: '26 - 28 Junio 2026',
    fechaInicioISO: '2026-06-26T10:00:00',
    finDeSemanaClave: '2026-W26',
    mesIdx: 5,
    comunidad: 'Cantabria',
    ciudad: 'Santander',
    recinto: 'Palacio de Exposiciones de Santander',
    direccion: 'Palacio de Exposiciones y Congresos de Santander, C. Real Racing Club, 3, 39005 Santander, Cantabria',
    categoria: 'comic',
    estado: 'CONFIRMADO',
    badges: ['Cómic', 'Ilustración'],
    descripcion: 'Cómic e ilustración en Cantabria.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://www.instagram.com/santandercomic/'
  },

  // ==================== JULIO (mesIdx: 6) ====================
  {
    id: 'metropoli-comic-con-gijon',
    nombre: 'Metrópoli Comic Con Gijón',
    fechas: '3 - 5 Julio 2026',
    fechaInicioISO: '2026-07-03T11:00:00',
    finDeSemanaClave: '2026-W27',
    mesIdx: 6,
    comunidad: 'Asturias',
    ciudad: 'Gijón (Asturias)',
    recinto: 'Recinto Ferial Luis Adaro',
    direccion: 'Recinto Ferial Luis Adaro, Paseo Doctor Fleming, 481, 33203 Gijón, Asturias',
    categoria: 'comic',
    estado: 'PROGRAMA OFICIAL',
    badges: ['Cómic USA', 'Cine', 'Estrellas'],
    descripcion: 'Cómic USA, cine y estrellas invitadas.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://metropoligijon.com'
  },
  {
    id: 'gamepolis-malaga',
    nombre: 'GamePolis',
    fechas: '18 - 19 Julio 2026',
    fechaInicioISO: '2026-07-18T10:00:00',
    finDeSemanaClave: '2026-W29',
    mesIdx: 6,
    comunidad: 'Andalucía',
    ciudad: 'Málaga Capital',
    recinto: 'FYCMA Málaga',
    direccion: 'FYCMA, C. José Ortega y Gasset, 201, Cruz de Humilladero, 29006 Málaga',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Videojuegos', 'Indies', 'Esports'],
    descripcion: 'Festival de videojuegos, indies y esports.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://gamepolis.org'
  },
  {
    id: 'esports-city-fest-andorra',
    nombre: 'Esports City Fest Andorra',
    fechas: '25 - 26 Julio 2026',
    fechaInicioISO: '2026-07-25T10:00:00',
    finDeSemanaClave: '2026-W30',
    mesIdx: 6,
    comunidad: 'Andorra / Pirineos',
    ciudad: 'Andorra la Vella',
    recinto: 'Centre de Congressos',
    direccion: 'Centre de Congressos d\'Andorra la Vella, Plaça del Poble, s/n, AD500 Andorra la Vella',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Gaming Pirineos', 'Esports'],
    descripcion: 'Gaming en los Pirineos y competiciones.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://esportscityfest.com'
  },

  // ==================== AGOSTO (mesIdx: 7) ====================
  {
    id: 'summerbit',
    nombre: 'SummerBit',
    fechas: '1 Agosto 2026',
    fechaInicioISO: '2026-08-01T10:00:00',
    finDeSemanaClave: '2026-W31',
    mesIdx: 7,
    comunidad: 'Madrid',
    ciudad: 'Madrid',
    recinto: 'Recinto Ferial',
    direccion: 'Pabellón de Cristal, Av. Principal, 16, 28011 Madrid',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Retro', 'Digital'],
    descripcion: 'Videojuegos retro y cultura digital.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://summerbit.es'
  },
  {
    id: 'sweetglitch-weekend',
    nombre: 'SweetGlitch Weekend',
    fechas: '8 - 9 Agosto 2026',
    fechaInicioISO: '2026-08-08T10:00:00',
    finDeSemanaClave: '2026-W32',
    mesIdx: 7,
    comunidad: 'Comunitat Valenciana',
    ciudad: 'Valencia',
    recinto: 'Espacio Joven',
    direccion: 'Feria Valencia, Avinguda de les Fires, s/n, 46035 València',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Ocio Alternativo', 'Anime'],
    descripcion: 'Ocio alternativo y anime estival.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: '#'
  },
  {
    id: 'cepazocon',
    nombre: 'CEPAZOCON',
    fechas: '14 - 16 Agosto 2026',
    fechaInicioISO: '2026-08-14T12:00:00',
    finDeSemanaClave: '2026-W33',
    mesIdx: 7,
    comunidad: 'Castilla y León',
    ciudad: 'Valladolid',
    recinto: 'Albergue y Espacio Polivalente',
    direccion: 'Feria de Valladolid, Av. Ramón Pradera, 3, 47009 Valladolid',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Rol', 'Juegos de Mesa', 'Convivencia'],
    descripcion: 'Encuentro de rol, juegos de mesa y convivencia friki.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://www.instagram.com/cepazo/'
  },
  {
    id: 'comic-digital-fest',
    nombre: 'C&D 2026',
    fechas: '21 - 23 Agosto 2026',
    fechaInicioISO: '2026-08-21T10:00:00',
    finDeSemanaClave: '2026-W34',
    mesIdx: 7,
    comunidad: 'Andalucía',
    ciudad: 'Málaga',
    recinto: 'Palacio de Congresos',
    direccion: 'Palacio de Congresos de Torremolinos, C. México, 3, 29620 Torremolinos, Málaga',
    categoria: 'comic',
    estado: 'CONFIRMADO',
    badges: ['Cómic', 'Digital'],
    descripcion: 'Comic & Digital fest estival.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: '#'
  },

  // ==================== SEPTIEMBRE (mesIdx: 8) ====================
  {
    id: 'gran-canaria-gaming',
    nombre: 'Gran Canaria Gaming Experience',
    fechas: '2 - 6 Septiembre 2026',
    fechaInicioISO: '2026-09-02T10:00:00',
    finDeSemanaClave: '2026-W36',
    mesIdx: 8,
    comunidad: 'Canarias',
    ciudad: 'Las Palmas de Gran Canaria',
    recinto: 'INFECAR',
    direccion: 'INFECAR Feria de Gran Canaria, Av. de la Feria, 1, 35012 Las Palmas de Gran Canaria',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Tecnología', 'Videojuegos'],
    descripcion: 'Tecnología y videojuegos en INFECAR.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: '#'
  },
  {
    id: 'navarra-lan-party',
    nombre: 'Navarra LAN Party',
    fechas: '3 - 6 Septiembre 2026',
    fechaInicioISO: '2026-09-03T10:00:00',
    finDeSemanaClave: '2026-W36',
    mesIdx: 8,
    comunidad: 'Navarra',
    ciudad: 'Pamplona',
    recinto: 'Navarra Arena',
    direccion: 'Navarra Arena, Plaza Aizagerria, 1, 31006 Pamplona, Navarra',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['LAN Party', 'Hardware'],
    descripcion: 'LAN party y hardware en Navarra Arena.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://navarralanparty.org'
  },
  {
    id: 'cometcon-asturias',
    nombre: "CometCon '26",
    fechas: '4 - 6 Septiembre 2026',
    fechaInicioISO: '2026-09-04T10:00:00',
    finDeSemanaClave: '2026-W36',
    mesIdx: 8,
    comunidad: 'Asturias',
    ciudad: 'Gijón (Asturias)',
    recinto: 'Recinto Ferial Luis Adaro',
    direccion: 'Recinto Ferial Luis Adaro, Paseo Doctor Fleming, 481, 33203 Gijón, Asturias',
    categoria: 'comic',
    estado: 'PROGRAMA OFICIAL',
    badges: ['Cómic', 'Cosplay', 'Gaming'],
    descripcion: 'Macroconvención juvenil de cómic, cosplay y gaming.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://cometcon.org'
  },
  {
    id: 'festival-manga-cadiz',
    nombre: 'Festival Manga de Cádiz',
    fechas: '4 - 6 Septiembre 2026',
    fechaInicioISO: '2026-09-04T11:00:00',
    finDeSemanaClave: '2026-W36',
    mesIdx: 8,
    comunidad: 'Andalucía',
    ciudad: 'Cádiz',
    recinto: 'Castillo de San Sebastián / IFECA',
    direccion: 'Castillo de San Sebastián, Paseo Fernando Quiñones, s/n, 11002 Cádiz',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Manga', 'Cosplay Costero'],
    descripcion: 'Manga y cosplay costero en Cádiz.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://femanca.com'
  },
  {
    id: 'fancon-sant-feliu',
    nombre: 'XIII FANCON',
    fechas: '4 - 6 Septiembre 2026',
    fechaInicioISO: '2026-09-04T16:00:00',
    finDeSemanaClave: '2026-W36',
    mesIdx: 8,
    comunidad: 'Cataluña',
    ciudad: 'Sant Feliu de Llobregat (Barcelona)',
    recinto: 'Palau Falguera',
    direccion: 'Palau Falguera, Carrer de Falguera, 6, 08980 Sant Feliu de Llobregat, Barcelona',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Ocio Alternativo', 'Rol'],
    descripcion: 'Festival internacional de ocio alternativo y rol.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://fancon.es'
  },
  {
    id: 'festival-juegos-cordoba',
    nombre: 'XXI Festival Internacional de Juegos Córdoba',
    fechas: '4 - 6 Septiembre 2026',
    fechaInicioISO: '2026-09-04T10:00:00',
    finDeSemanaClave: '2026-W36',
    mesIdx: 8,
    comunidad: 'Andalucía',
    ciudad: 'Córdoba',
    recinto: 'Palacio de la Merced',
    direccion: 'Palacio de la Merced, Plaza de Colón, 15, 14001 Córdoba',
    categoria: 'gaming',
    estado: 'PROGRAMA OFICIAL',
    badges: ['Juegos de Mesa', 'Referente'],
    descripcion: 'El mayor festival de juegos de mesa de España.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://jugamosla.com'
  },
  {
    id: 'salon-comic-navarra',
    nombre: 'XVII Salón del Cómic de Navarra',
    fechas: '4 - 27 Septiembre 2026',
    fechaInicioISO: '2026-09-04T10:00:00',
    finDeSemanaClave: '2026-W36',
    mesIdx: 8,
    comunidad: 'Navarra',
    ciudad: 'Pamplona',
    recinto: 'Condestable',
    direccion: 'Palacio del Condestable, C. Mayor, 2, 31001 Pamplona, Navarra',
    categoria: 'comic',
    estado: 'CONFIRMADO',
    badges: ['Mes del Cómic', 'Autor'],
    descripcion: 'Mes del cómic de autor con exposiciones y charlas.',
    tienePrograma: false,
    cartel: 'https://salondelcomicdenavarra.com/wp-content/uploads/2026/08/SALON-DEL-COMIC-NAVARRA-2026-COLS-scaled.jpg',
    enlaceExterno: 'https://salondelcomicdenavarra.com'
  },
  {
    id: 'infrefest-hospitalet',
    nombre: 'INFREFEST 2026',
    fechas: '5 - 6 Septiembre 2026',
    fechaInicioISO: '2026-09-05T09:30:00',
    finDeSemanaClave: '2026-W36',
    mesIdx: 8,
    comunidad: 'Cataluña',
    ciudad: "L'Hospitalet de Llobregat (Barcelona)",
    recinto: 'La Farga de L\'Hospitalet',
    direccion: 'La Farga Centro de Actividades, Carrer de Barcelona, 2, 08901 L\'Hospitalet de Llobregat, Barcelona',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Magic TCG', 'TCG', 'Rol'],
    descripcion: 'Macrofestival de Magic: The Gathering, TCGs y rol.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://infrefest.com'
  },
  {
    id: 'jornadas-comic-aviles',
    nombre: '31 Jornadas del Cómic Villa de Avilés',
    fechas: '8 - 12 Septiembre 2026',
    fechaInicioISO: '2026-09-08T11:00:00',
    finDeSemanaClave: '2026-W37',
    mesIdx: 8,
    comunidad: 'Asturias',
    ciudad: 'Avilés (Asturias)',
    recinto: 'Casa de Cultura',
    direccion: 'Casa Municipal de Cultura de Avilés, Pl. Domingo Álvarez Acebal, 2, 33402 Avilés, Asturias',
    categoria: 'comic',
    estado: 'CONFIRMADO',
    badges: ['Ilustradores', 'Firmas'],
    descripcion: 'Cita con ilustradores mundiales y firmas de autor.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://www.facebook.com/comicaviles/'
  },
  {
    id: 'ubuparty-burgos',
    nombre: 'UBUPARTY',
    fechas: '9 - 13 Septiembre 2026',
    fechaInicioISO: '2026-09-09T10:00:00',
    finDeSemanaClave: '2026-W37',
    mesIdx: 8,
    comunidad: 'Castilla y León',
    ciudad: 'Burgos',
    recinto: 'Polideportivo UBU',
    direccion: 'Polideportivo Universitario UBU, C. Villadiego, 1, 09001 Burgos',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Party Informática', 'Esports'],
    descripcion: 'Party informática y esports en Burgos.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://ubuparty.es'
  },
  {
    id: 'freak-wars-madrid',
    nombre: "Freak Wars '26",
    fechas: '12 - 13 Septiembre 2026',
    fechaInicioISO: '2026-09-12T10:00:00',
    finDeSemanaClave: '2026-W37',
    mesIdx: 8,
    comunidad: 'Madrid',
    ciudad: 'Madrid Capital',
    recinto: 'Pabellón de Cristal',
    direccion: 'Pabellón de Cristal, C. de las Aves, s/n, Moncloa - Aravaca, 28011 Madrid',
    categoria: 'gaming',
    estado: 'PROGRAMA OFICIAL',
    badges: ['Wargames', 'Miniaturas', 'Cosplay'],
    descripcion: 'El mayor evento europeo de wargames, miniaturas y cosplay.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://freakwarsmadrid.com'
  },
  {
    id: 'lerez-up-pontevedra',
    nombre: 'Lérez Up',
    fechas: '12 - 13 Septiembre 2026',
    fechaInicioISO: '2026-09-12T10:00:00',
    finDeSemanaClave: '2026-W37',
    mesIdx: 8,
    comunidad: 'Galicia',
    ciudad: 'Pontevedra',
    recinto: 'Recinto Feiral de Pontevedra',
    direccion: 'Recinto Feiral de Pontevedra, Rúa Alexandre Bóveda, 1, 36005 Pontevedra',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Videojuegos', 'Cultura Geek'],
    descripcion: 'Salón de videojuegos y cultura geek de Galicia.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://lerezup.es'
  },
  {
    id: 'mangacon-lleida',
    nombre: 'MangaCon Lleida',
    fechas: '12 - 13 Septiembre 2026',
    fechaInicioISO: '2026-09-12T10:00:00',
    finDeSemanaClave: '2026-W37',
    mesIdx: 8,
    comunidad: 'Cataluña',
    ciudad: 'Lleida',
    recinto: 'Pavelló Barris Nord',
    direccion: 'Pavelló Barris Nord, Carrer d\'Ausiàs March, 3, 25005 Lleida',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Manga', 'Ocio Juvenil'],
    descripcion: 'Salón del manga y ocio juvenil de Ponent.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://www.instagram.com/mangaconlleida/'
  },
  {
    id: 'rol-i-jocs-valencia',
    nombre: 'ROL & JOCS',
    fechas: '13 Septiembre 2026',
    fechaInicioISO: '2026-09-13T10:00:00',
    finDeSemanaClave: '2026-W37',
    mesIdx: 8,
    comunidad: 'Comunitat Valenciana',
    ciudad: 'Valencia',
    recinto: 'Centro Cívico y Juvenil',
    direccion: 'Feria Valencia, Avinguda de les Fires, s/n, 46035 València',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Rol Narrativo', 'Juegos de Mesa'],
    descripcion: 'Jornadas dedicadas al rol narrativo y de mesa.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: '#'
  },
  {
    id: 'galician-freaky-film',
    nombre: 'X Galician Freaky Film Festival',
    fechas: '17 - 26 Septiembre 2026',
    fechaInicioISO: '2026-09-17T17:00:00',
    finDeSemanaClave: '2026-W38',
    mesIdx: 8,
    comunidad: 'Galicia',
    ciudad: 'Vigo (Pontevedra)',
    recinto: 'Cines Tamberlick',
    direccion: 'Cines Tamberlick, Rúa de Eduardo Iglesias, 8, 36202 Vigo, Pontevedra',
    categoria: 'comic',
    estado: 'CONFIRMADO',
    badges: ['Cine Fantástico', 'Serie B'],
    descripcion: 'Cine fantástico, serie B y cultura friki.',
    tienePrograma: false,
    cartel: 'https://galicianfreakyfestival.com/wp-content/uploads/2026/09/GFFF-IG-2026_Final-1038x1280.webp',
    enlaceExterno: 'https://galicianfreakyfestival.com/'
  },
  {
    id: 'ludo-ergo-sum-madrid',
    nombre: 'Ludo Ergo Sum',
    fechas: '18 - 20 Septiembre 2026',
    fechaInicioISO: '2026-09-18T16:00:00',
    finDeSemanaClave: '2026-W38',
    mesIdx: 8,
    comunidad: 'Madrid',
    ciudad: 'Alcorcón / Madrid',
    recinto: 'Polideportivo Los Cantos',
    direccion: 'Polideportivo Los Cantos, Av. de los Cantos, 28, 28922 Alcorcón, Madrid',
    categoria: 'gaming',
    estado: 'PROGRAMA OFICIAL',
    badges: ['Solidario', 'Juegos de Mesa', 'Rol'],
    descripcion: 'Jornadas solidarias de juegos de mesa, rol y miniaturas.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://ludoergosum.org'
  },
  {
    id: 'badaboom-badajoz',
    nombre: 'Badaboom Badajoz',
    fechas: '18 - 20 Septiembre 2026',
    fechaInicioISO: '2026-09-18T10:00:00',
    finDeSemanaClave: '2026-W38',
    mesIdx: 8,
    comunidad: 'Extremadura',
    ciudad: 'Badajoz',
    recinto: 'IFEBA',
    direccion: 'IFEBA, Av. de Elvas, s/n, 06006 Badajoz',
    categoria: 'comic',
    estado: 'CONFIRMADO',
    badges: ['Autoedición', 'Gráfica'],
    descripcion: 'Autoedición gráfica y cultura alternativa.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: '#'
  },
  {
    id: 'expotaku-irun',
    nombre: 'ExpOtaku Irún',
    fechas: '19 - 20 Septiembre 2026',
    fechaInicioISO: '2026-09-19T10:00:00',
    finDeSemanaClave: '2026-W38',
    mesIdx: 8,
    comunidad: 'Euskadi',
    ciudad: 'Irún (Gipuzkoa)',
    recinto: 'Ficoba',
    direccion: 'Ficoba, Anardi Plaza, 1, 20301 Irun, Gipuzkoa',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Manga', 'Ocio Euskadi'],
    descripcion: 'Manga y ocio alternativo en Euskadi.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://expotaku.com/irun'
  },
  {
    id: 'manchacomic-ciudad-real',
    nombre: 'XIII ManchaCómic!',
    fechas: '25 - 27 Septiembre 2026',
    fechaInicioISO: '2026-09-25T10:00:00',
    finDeSemanaClave: '2026-W39',
    mesIdx: 8,
    comunidad: 'Castilla-La Mancha',
    ciudad: 'Ciudad Real',
    recinto: 'Antiguo Casino',
    direccion: 'Antiguo Casino de Ciudad Real, C. Caballeros, 3, 13001 Ciudad Real',
    categoria: 'comic',
    estado: 'CONFIRMADO',
    badges: ['Salón del Cómic', 'Mancha'],
    descripcion: 'Salón del cómic de Castilla-La Mancha.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://manchacomic.es'
  },
  {
    id: 'dalle-xogo-santiago',
    nombre: 'Dálle Xogo',
    fechas: '25 - 27 Septiembre 2026',
    fechaInicioISO: '2026-09-25T16:00:00',
    finDeSemanaClave: '2026-W39',
    mesIdx: 8,
    comunidad: 'Galicia',
    ciudad: 'Santiago de Compostela',
    recinto: 'Centro Xuvenil Don Bosco',
    direccion: 'Centro Xuvenil Don Bosco, Rúa de Belvís, 2, 15703 Santiago de Compostela, A Coruña',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Juegos de Mesa', 'Rol'],
    descripcion: 'Juegos de mesa y rol en Galicia.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://dallexogo.gal'
  },
  {
    id: 'jw-madrid-septiembre',
    nombre: 'Japan Weekend Madrid',
    fechas: '26 - 27 Septiembre 2026',
    fechaInicioISO: '2026-09-26T10:00:00',
    finDeSemanaClave: '2026-W39',
    mesIdx: 8,
    comunidad: 'Madrid',
    ciudad: 'Madrid Capital',
    recinto: 'IFEMA Madrid',
    direccion: 'IFEMA Madrid, Av. del Partenón, 5, Barajas, 28042 Madrid',
    categoria: 'manga',
    estado: 'PROGRAMA OFICIAL',
    badges: ['Gran Convención', 'Otoño'],
    descripcion: 'La gran convención otaku de otoño en IFEMA.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://japanweekend.com/madrid/'
  },
  {
    id: 'mangafest-extremadura-deluxe',
    nombre: 'Mangafest Extremadura Deluxe',
    fechas: '26 - 27 Septiembre 2026',
    fechaInicioISO: '2026-09-26T10:00:00',
    finDeSemanaClave: '2026-W39',
    mesIdx: 8,
    comunidad: 'Extremadura',
    ciudad: 'Mérida / Badajoz',
    recinto: 'IFEBA / IFEME',
    direccion: 'IFEME - Institución Ferial de Mérida, C. Manuel Núñez, s/n, 06800 Mérida, Badajoz',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Festival Pop', 'Andaluz'],
    descripcion: 'Festival pop andaluz en tierras extremeñas.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://mangafest.es/extremadura/'
  },

  // ==================== OCTUBRE (mesIdx: 9) ====================
  {
    id: 'sdcc-malaga',
    nombre: 'San Diego Comic-Con Málaga',
    fechas: '1 - 4 Octubre 2026',
    fechaInicioISO: '2026-10-01T09:00:00',
    finDeSemanaClave: '2026-W40',
    mesIdx: 9,
    comunidad: 'Andalucía',
    ciudad: 'Málaga, Andalucía',
    recinto: 'FYCMA (Palacio de Ferias y Congresos)',
    direccion: 'FYCMA, C. José Ortega y Gasset, 201, Cruz de Humilladero, 29006 Málaga',
    categoria: 'comic',
    estado: 'PROGRAMA OFICIAL',
    badges: ['Cine & Series', 'Auditorios Hall M', 'Firmas VIP'],
    descripcion: 'Cine, series, cómics y actores de Hollywood en FYCMA.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://sandiegocomicconmalaga.com/'
  },
  {
    id: 'necrocon-hospitalet',
    nombre: 'NECROCON 2026',
    fechas: '2 - 4 Octubre 2026',
    fechaInicioISO: '2026-10-02T16:00:00',
    finDeSemanaClave: '2026-W40',
    mesIdx: 9,
    comunidad: 'Cataluña',
    ciudad: "L'Hospitalet de Llobregat (Barcelona)",
    recinto: 'Espai L\'Harmonia',
    direccion: 'Museu de L\'Hospitalet - Casa Espanya / L\'Harmonia, Carrer del Xipreret, 87, 08901 L\'Hospitalet de Llobregat, Barcelona',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Rol de Terror', 'Horror Cósmico'],
    descripcion: 'Convención de rol de terror y horror cósmico.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://necrocon.es'
  },
  {
    id: 'oh-comics-bcn',
    nombre: 'OH! Comics Fest Barcelona',
    fechas: '2 - 4 Octubre 2026',
    fechaInicioISO: '2026-10-02T17:30:00',
    finDeSemanaClave: '2026-W40',
    mesIdx: 9,
    comunidad: 'Cataluña',
    ciudad: 'Barcelona Capital',
    recinto: 'Institut Martí Pous (Recinte Fabra i Coats)',
    direccion: 'Institut Martí Pous, Carrer de Sant Adrià, 20, Sant Andreu, 08030 Barcelona',
    categoria: 'comic',
    estado: 'ENTRADA GRATUITA',
    badges: ['Autoedición', 'Fanzines', 'Entrada Gratis', 'Talleres'],
    descripcion: 'Festival de cómic alternativo, autoedición y fanzines. Más de 60 expositores, presentaciones y talleres.',
    tienePrograma: false,
    cartel: 'https://ohcomicsfest.com/bcn/2026/img/oh-comics-fest-bcn-2026-es-poster.jpg',
    enlaceExterno: 'https://ohcomicsfest.com/es/'
  },
  {
    id: 'jw-bilbao',
    nombre: 'Japan Weekend Bilbao',
    fechas: '3 Octubre 2026',
    fechaInicioISO: '2026-10-03T10:00:00',
    finDeSemanaClave: '2026-W40',
    mesIdx: 9,
    comunidad: 'Euskadi',
    ciudad: 'Bilbao (Bizkaia)',
    recinto: 'BEC! Barakaldo',
    direccion: 'Bilbao Exhibition Centre (BEC), Azkue Kalea, 1, 48902 Barakaldo, Bizkaia',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Manga', 'Cosplay Vasco'],
    descripcion: 'Manga y cosplay vasco en el BEC!',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://japanweekend.com/bilbao/'
  },
  {
    id: 'feria-manga-vila-joiosa',
    nombre: 'VI Feria del Manga de La Vila Joiosa',
    fechas: '3 Octubre 2026',
    fechaInicioISO: '2026-10-03T10:00:00',
    finDeSemanaClave: '2026-W40',
    mesIdx: 9,
    comunidad: 'Comunitat Valenciana',
    ciudad: 'La Vila Joiosa (Alicante)',
    recinto: 'Recinto Ferial Municipal',
    direccion: 'Llar del Pensionista, Carrer Huit de Maig, s/n, 03570 La Vila Joiosa, Alicante',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Difusión Japonesa', 'Talleres'],
    descripcion: 'Difusión japonesa y talleres culturales.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://www.instagram.com/feriamangavl/'
  },
  {
    id: 'mangamore-amorebieta',
    nombre: 'Mangamore Amorebieta',
    fechas: '9 - 11 Octubre 2026',
    fechaInicioISO: '2026-10-09T16:00:00',
    finDeSemanaClave: '2026-W41',
    mesIdx: 9,
    comunidad: 'Euskadi',
    ciudad: 'Amorebieta (Bizkaia)',
    recinto: 'Zelaieta',
    direccion: 'Zelaieta Zentroa, Zelaieta Parkea, s/n, 48370 Amorebieta-Etxano, Bizkaia',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Festival Japonés', 'Aire Libre'],
    descripcion: 'Festival japonés al aire libre con conciertos.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://mangamore.eus'
  },
  {
    id: 'frikiing-days-andorra',
    nombre: 'Frikiing Days Andorra',
    fechas: '9 - 11 Octubre 2026',
    fechaInicioISO: '2026-10-09T17:00:00',
    finDeSemanaClave: '2026-W41',
    mesIdx: 9,
    comunidad: 'Andorra / Pirineos',
    ciudad: 'Encamp (Andorra)',
    recinto: 'Complex Esportiu d\'Encamp',
    direccion: 'Complex Esportiu i Sociocultural d\'Encamp, Carrer de les Escoles, s/n, AD200 Encamp',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Magic', 'Rol', 'Warhammer'],
    descripcion: 'Magic, rol y Warhammer en los Pirineos.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://www.instagram.com/frikiing_days/'
  },
  {
    id: 'girocomic',
    nombre: 'Girocòmic',
    fechas: '10 - 12 Octubre 2026',
    fechaInicioISO: '2026-10-10T10:00:00',
    finDeSemanaClave: '2026-W41',
    mesIdx: 9,
    comunidad: 'Cataluña',
    ciudad: 'Girona',
    recinto: 'Fira de Girona',
    direccion: 'Palau de Fires de Girona, Passeig de la Devesa, 34, 17001 Girona',
    categoria: 'comic',
    estado: 'CONFIRMADO',
    badges: ['Cómic', 'Ilustración'],
    descripcion: 'Cómic e ilustración en Girona.',
    tienePrograma: false,
    cartel: 'https://www.girocomic.cat/media/content/Cartell%202026-color1779691809969.jpg?rnd=1779691815538',
    enlaceExterno: 'https://girocomic.cat'
  },
  {
    id: 'comic-granada',
    nombre: '32 Salón Internacional del Cómic de Granada',
    fechas: '16 - 18 Octubre 2026',
    fechaInicioISO: '2026-10-16T11:00:00',
    finDeSemanaClave: '2026-W42',
    mesIdx: 9,
    comunidad: 'Andalucía',
    ciudad: 'Granada (Armilla)',
    recinto: 'Fermasa',
    direccion: 'FERMASA, Ctra. de Armilla, s/n, 18100 Armilla, Granada',
    categoria: 'comic',
    estado: 'FECHAS CONFIRMADAS',
    badges: ['Editores USA', 'Firmas'],
    descripcion: 'Entrevistas con editores internacionales y cómic clásico.',
    tienePrograma: false,
    cartel: 'https://saloncomicgranada.com/wp-content/uploads/2026/09/cartel-salon-internacional-comic-granada-2026-danay-dana.jpg',
    enlaceExterno: 'https://saloncomicgranada.com'
  },
  {
    id: 'friki-con-sevilla-nueva',
    nombre: 'Friki-Con',
    fechas: '17 - 18 Octubre 2026',
    fechaInicioISO: '2026-10-17T10:00:00',
    finDeSemanaClave: '2026-W42',
    mesIdx: 9,
    comunidad: 'Madrid',
    ciudad: 'Sevilla la Nueva (Madrid)',
    recinto: 'Pabellón Adolfo Suárez',
    direccion: 'Polideportivo Municipal Adolfo Suárez, C. Ruiseñor, s/n, 28690 Sevilla la Nueva, Madrid',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Ocio Familiar', 'Retro'],
    descripcion: 'Ocio familiar, juegos de mesa y retro.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://www.instagram.com/frikiconsevilla/'
  },
  {
    id: 'huetor-tajar-go',
    nombre: 'Huétor-Tájar GO!',
    fechas: '17 - 18 Octubre 2026',
    fechaInicioISO: '2026-10-17T10:30:00',
    finDeSemanaClave: '2026-W42',
    mesIdx: 9,
    comunidad: 'Andalucía',
    ciudad: 'Huétor Tájar (Granada)',
    recinto: 'Pabellón Multiusos',
    direccion: 'Pabellón Multiusos Recinto Ferial, 18360 Huétor Tájar, Granada',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Gaming Juvenil', 'VR'],
    descripcion: 'Gaming juvenil, realidad virtual y talleres.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://eventosgo.es'
  },
  {
    id: 'madrid-otaku',
    nombre: 'Madrid Otaku',
    fechas: '23 - 25 Octubre 2026',
    fechaInicioISO: '2026-10-23T10:00:00',
    finDeSemanaClave: '2026-W43',
    mesIdx: 9,
    comunidad: 'Madrid',
    ciudad: 'Madrid Capital',
    recinto: 'Caja Mágica',
    direccion: 'Caja Mágica, Cam. de Perales, 23, Usera, 28041 Madrid',
    categoria: 'manga',
    estado: 'ENTRADAS DISPONIBLES',
    badges: ['Tradición Japonesa', 'J-Music'],
    descripcion: 'Cultura tradicional japonesa y J-Music en la Caja Mágica.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://madridotaku.com'
  },
  {
    id: 'inca-yokai-fest',
    nombre: 'Inca Yokai Fest',
    fechas: '23 - 25 Octubre 2026',
    fechaInicioISO: '2026-10-23T17:00:00',
    finDeSemanaClave: '2026-W43',
    mesIdx: 9,
    comunidad: 'Islas Baleares',
    ciudad: 'Inca (Mallorca)',
    recinto: 'Fàbrica Ramis',
    direccion: 'Fàbrica Ramis, Gran Via de Colom, 28, 07300 Inca, Illes Balears',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Mitología', 'Folclore Nipón'],
    descripcion: 'Mitología y folclore nipón en Mallorca.',
    tienePrograma: false,
    cartel: 'https://incayokaifest.es/img/about/cartelganador2026.jpg',
    enlaceExterno: 'https://incayokaifest.es'
  },
  {
    id: 'expotaku-granada',
    nombre: 'ExpOtaku Granada',
    fechas: '24 - 25 Octubre 2026',
    fechaInicioISO: '2026-10-24T10:00:00',
    finDeSemanaClave: '2026-W43',
    mesIdx: 9,
    comunidad: 'Andalucía',
    ciudad: 'Granada (Armilla)',
    recinto: 'FERMASA',
    direccion: 'FERMASA, Ctra. de Armilla, s/n, 18100 Armilla, Granada',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['K-Pop', 'Anime'],
    descripcion: 'K-Pop, anime y tiendas en Fermasa.',
    tienePrograma: false,
    cartel: 'https://www.expotaku.com/imagenes/EOG2026.jpg',
    enlaceExterno: 'https://expotaku.com/granada'
  },

  // ==================== NOVIEMBRE (mesIdx: 10) ====================
  {
    id: 'manga-murcia',
    nombre: 'XVIII Salón del Manga de Murcia (Murcia se Remanga)',
    fechas: '13 - 15 Noviembre 2026',
    fechaInicioISO: '2026-11-13T10:00:00',
    finDeSemanaClave: '2026-W46',
    mesIdx: 10,
    comunidad: 'Región de Murcia',
    ciudad: 'Murcia Capital',
    recinto: 'Auditorio Víctor Villegas',
    direccion: 'Auditorio y Centro de Congresos Víctor Villegas, Av. Primero de Mayo, s/n, 30006 Murcia',
    categoria: 'manga',
    estado: 'FECHAS CONFIRMADAS',
    badges: ['Murcia se Remanga', 'Cosplay'],
    descripcion: 'Murcia se Remanga: cita referente del manga en el levante.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://murciaseremanga.es'
  },
  {
    id: 'heroes-comic-con-madrid',
    nombre: 'Heroes Comic Con Madrid',
    fechas: '14 - 15 Noviembre 2026',
    fechaInicioISO: '2026-11-14T10:00:00',
    finDeSemanaClave: '2026-W46',
    mesIdx: 10,
    comunidad: 'Madrid',
    ciudad: 'Madrid Capital',
    recinto: 'IFEMA Madrid',
    direccion: 'IFEMA Madrid, Av. del Partenón, 5, Barajas, 28042 Madrid',
    categoria: 'comic',
    estado: 'PROGRAMA OFICIAL',
    badges: ['Cómic Americano', 'Cine'],
    descripcion: 'Cómic americano, actores invitados y cine en IFEMA.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://www.heroescomicconmadrid.com'
  },
  {
    id: 'expotaku-coruna-otono',
    nombre: 'ExpOtaku A Coruña',
    fechas: '20 - 22 Noviembre 2026',
    fechaInicioISO: '2026-11-20T16:00:00',
    finDeSemanaClave: '2026-W47',
    mesIdx: 10,
    comunidad: 'Galicia',
    ciudad: 'A Coruña',
    recinto: 'ExpoCoruña',
    direccion: 'ExpoCoruña, Rúa Juana Capdevielle, 2, 15008 A Coruña',
    categoria: 'manga',
    estado: 'CONFIRMADO',
    badges: ['Cultura Otaku', 'Otoño'],
    descripcion: 'Edición de otoño gallega en ExpoCoruña.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://expotaku.com/a-coruna'
  },
  {
    id: 'jw-valencia-otono',
    nombre: 'Japan Weekend Valencia',
    fechas: '21 - 22 Noviembre 2026',
    fechaInicioISO: '2026-11-21T10:00:00',
    finDeSemanaClave: '2026-W47',
    mesIdx: 10,
    comunidad: 'Comunitat Valenciana',
    ciudad: 'Valencia Capital',
    recinto: 'Feria Valencia',
    direccion: 'Feria Valencia, Avinguda de les Fires, s/n, Pobles de l\'Oest, 46035 València',
    categoria: 'manga',
    estado: 'ENTRADAS A LA VENTA',
    badges: ['Manga', 'Cosplay Levantino'],
    descripcion: 'Manga y cosplay levantino en Feria Valencia.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://japanweekend.com/valencia/'
  },
  {
    id: 'mangah-o',
    nombre: 'III MANGAH-O',
    fechas: '27 - 29 Noviembre 2026',
    fechaInicioISO: '2026-11-27T17:00:00',
    finDeSemanaClave: '2026-W48',
    mesIdx: 10,
    comunidad: 'Andalucía',
    ciudad: 'Huércal-Overa (Almería)',
    recinto: 'Recinto Ferial de Huércal-Overa',
    direccion: 'Recinto Ferial de Huércal-Overa, 04600 Huércal-Overa, Almería',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Ocio Digital', 'Comarcal'],
    descripcion: 'Ocio digital y cultura japonesa en Almería.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://www.instagram.com/mangaho_huercalovera/'
  },

  // ==================== DICIEMBRE (mesIdx: 11) ====================
  {
    id: 'manga-barcelona',
    nombre: '32 Manga Barcelona',
    fechas: '5 - 8 Diciembre 2026',
    fechaInicioISO: '2026-12-05T10:00:00',
    finDeSemanaClave: '2026-W49',
    mesIdx: 11,
    comunidad: 'Cataluña',
    ciudad: "L'Hospitalet / Barcelona",
    recinto: 'Fira Gran Via',
    direccion: 'Fira Barcelona Gran Via, Carrer del Foc, 10, Sants-Montjuïc, 08038 Barcelona',
    categoria: 'manga',
    estado: 'GRAN CITA ANUAL',
    badges: ['Líder Europa', '5 Pabellones'],
    descripcion: 'El macroevento líder de Europa en cultura japonesa y manga.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://www.manga-barcelona.com'
  },
  {
    id: 'mangafest-sevilla',
    nombre: 'Mangafest Sevilla',
    fechas: '5 - 7 Diciembre 2026',
    fechaInicioISO: '2026-12-05T10:00:00',
    finDeSemanaClave: '2026-W49',
    mesIdx: 11,
    comunidad: 'Andalucía',
    ciudad: 'Sevilla',
    recinto: 'FIBES Sevilla',
    direccion: 'FIBES - Palacio de Congresos y Exposiciones, Av. Alcalde Luis Uruñuela, 1, 41020 Sevilla',
    categoria: 'gaming',
    estado: 'CONFIRMADO',
    badges: ['Macrofestival', 'Gaming Invierno'],
    descripcion: 'Macrofestival gaming de invierno en FIBES.',
    tienePrograma: false,
    cartel: '',
    enlaceExterno: 'https://mangafest.es'
  }
];
